-- ============================================
-- FBR POST RESPONSE MIGRATION
-- ============================================
-- Run this SQL in Supabase SQL Editor to add fields for storing FBR post response
-- Copy and paste this entire file into Supabase SQL Editor and execute

-- ============================================
-- 1. ADD FIELDS TO INVOICES TABLE
-- ============================================

-- Add FBR invoice number field (generated by FBR)
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS fbr_invoice_number VARCHAR(100);

-- Add FBR response field (stores complete FBR response as JSON)
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS fbr_response JSONB;

-- Add comments to new columns
COMMENT ON COLUMN invoices.fbr_invoice_number IS 'FBR generated invoice number (e.g., 7000007DI1747119701593-1)';
COMMENT ON COLUMN invoices.fbr_response IS 'Complete FBR API response stored as JSON';

-- ============================================
-- 2. CREATE INDEXES FOR PERFORMANCE
-- ============================================

-- Create index on FBR invoice number for faster lookups
CREATE INDEX IF NOT EXISTS idx_invoices_fbr_invoice_number ON invoices(fbr_invoice_number);

-- Create GIN index on FBR response JSONB for faster JSON queries
CREATE INDEX IF NOT EXISTS idx_invoices_fbr_response ON invoices USING GIN (fbr_response);

-- ============================================
-- 3. VERIFICATION QUERIES
-- ============================================
-- Run these queries after migration to verify the changes

-- Verify invoices table structure
-- SELECT column_name, data_type, character_maximum_length, is_nullable
-- FROM information_schema.columns
-- WHERE table_name = 'invoices'
-- AND column_name IN ('fbr_invoice_number', 'fbr_response')
-- ORDER BY column_name;

-- Check invoices with FBR data
-- SELECT id, invoice_number, fbr_invoice_number, status, fbr_posted_at
-- FROM invoices
-- WHERE fbr_invoice_number IS NOT NULL
-- LIMIT 5;

-- Check FBR response data
-- SELECT id, invoice_number, fbr_response
-- FROM invoices
-- WHERE fbr_response IS NOT NULL
-- LIMIT 5;

-- ============================================
-- MIGRATION COMPLETE
-- ============================================
-- All fields required for storing FBR post response have been added successfully!

