-- Create announcements table
CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  image_path VARCHAR(500),
  created_by BIGINT, -- FK to admin users (assuming users table or similar, but keeping loose for now or strictly referencing if known)
  is_deleted SMALLINT DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create announcement_views table
CREATE TABLE IF NOT EXISTS announcement_views (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  announcement_id BIGINT REFERENCES announcements(id) ON DELETE CASCADE,
  seller_id BIGINT, -- FK to sellers (assuming sellers table exists)
  viewed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_announcements_is_deleted ON announcements(is_deleted);
CREATE INDEX IF NOT EXISTS idx_announcement_views_seller_id ON announcement_views(seller_id);
CREATE INDEX IF NOT EXISTS idx_announcement_views_announcement_id ON announcement_views(announcement_id);
