import { NextResponse } from 'next/server';
import { getSupabaseServer } from '@/lib/supabase-server';

export async function GET() {
    const supabase = getSupabaseServer();

    try {
        // Create announcements table
        const { error: announcementsError } = await supabase.rpc('setup_announcements_tables');

        if (announcementsError) {
            // If RPC fails (likely because function doesn't exist), try direct SQL via RPC if enabled, 
            // or fall back to creating via raw query if possible (Supabase JS client doesn't support raw SQL directly usually).
            // However, since we can't run raw SQL easily without a specific RPC, we will try to use the 'rpc' method 
            // assuming a 'exec_sql' or similar function exists, OR we will assume the user needs to run this manually 
            // if we can't find a way. 

            // BUT, for this environment, let's try to see if we can use the `pg` library or similar if installed?
            // Checking package.json would have been good. 

            // actually, let's try to create a function via RPC if possible, or just use the fact that 
            // we might not be able to run DDL from here easily without a helper.

            // WAIT: The user asked to "Add a new table". Usually this implies I should provide the SQL or run it.
            // If I can't run it, I'll have to ask the user.
            // But let's try to see if there is a `query` or similar method on the supabase client or if I can use `postgres.js` if available.

            return NextResponse.json({
                error: 'Cannot run DDL directly from client. Please run the following SQL in your Supabase SQL Editor:',
                sql: `
          CREATE TABLE IF NOT EXISTS announcements (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title VARCHAR(255) NOT NULL,
            description TEXT NOT NULL,
            image_path VARCHAR(500),
            created_by BIGINT,
            is_deleted SMALLINT DEFAULT 0,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
          );

          CREATE TABLE IF NOT EXISTS announcement_views (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            announcement_id BIGINT REFERENCES announcements(id) ON DELETE CASCADE,
            seller_id BIGINT,
            viewed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
          );
        `
            }, { status: 500 });
        }

        return NextResponse.json({ message: 'Tables created successfully' });
    } catch (error: any) {
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
